# Generated by Django 3.2.11 on 2022-05-14 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='datetime_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 18, 24, 26, 687149)),
        ),
    ]
