# Generated by Django 3.2.11 on 2022-05-14 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_patron_datetime_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='datetime_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 22, 33, 19, 683231, tzinfo=utc)),
        ),
    ]
