# Generated by Django 3.2.11 on 2022-05-15 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patron_datetime_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='datetime_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
