# Generated by Django 3.2.11 on 2022-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_patron_datetime_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
