# Generated by Django 3.2.11 on 2022-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220515_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='total_passports',
            field=models.IntegerField(default=1),
        ),
    ]
