# Generated by Django 3.2.11 on 2022-05-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_patron_total_passports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
