# Generated by Django 3.2.11 on 2022-05-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_patron_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='photo_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
