# Generated by Django 3.2.11 on 2022-05-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_patron_photo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='photo_status',
            field=models.BooleanField(default=False),
        ),
    ]
