# Generated by Django 3.2.11 on 2022-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_patron_photo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='datetime_finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='datetime_started',
            field=models.DateTimeField(null=True),
        ),
    ]
