# Generated by Django 3.2.11 on 2022-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220523_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='datetime_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='datetime_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
