# Generated by Django 3.2.11 on 2022-10-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220523_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='patron',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
